name: CI
on:
  push:
    branches: [ "main" ]
jobs:  
    trivy:
      runs-on: ubuntu-20.04
      steps:
        - name: Login Docker
          run: echo "${{ secrets.REGISTRY_PASSWORD }}" | docker login ${{secrets.REGISTRY_ENDPOINT}} -u "${{ secrets.REGISTRY_USERNAME }}" --password-stdin
           #echo "{ \"auths\": { \"${{ secrets.registry_endpoint }}\": { \"auth\": \"$(echo ${{ secrets.registry_username }}:${{ secrets.registry_password }} | base64 )\" }}}" > password.txt
        
        - name: Docker pull
          run: docker pull tcr.tks.trueidc.com/crm/crm-backend:main
          
        - name: Run Trivy vulnerability scanner
          uses: aquasecurity/trivy-action@master
          with:
            image-ref: tcr.tks.trueidc.com/crm/crm-backend:main
          #  image-ref: '${{ secrets.registry_endpoint }}/${{secrets.registry_team}}/${{secrets.registry_project}}:main'
            format: 'sarif'
            output: 'trivy-results.sarif'
  
        - name: Upload Trivy scan results to GitHub Security tab
          uses: github/codeql-action/upload-sarif@v2
          with:
            sarif_file: 'trivy-results.sarif'
