name: CI
on:
  push:
    branches: [ "main" ]
jobs:  
    trivy:
      runs-on: ubuntu-20.04
#      permissions:
#        actions: read
#        contents: read
#        security-events: write
      permissions: write-all
      steps:
        - name: Login Docker
          run: echo "a0gqGcYR0dP4xhZDgtqvY0sHi6sj85VM" | docker login "tcr.tks.trueidc.com" -u 'robot$cluster0' --password-stdin
        
        - name: Docker pull
          run: docker pull tcr.tks.trueidc.com/crm/crm-backend:vulner
          
        - name: Run Trivy vulnerability scanner
          uses: aquasecurity/trivy-action@master
          with:
            image-ref: tcr.tks.trueidc.com/crm/crm-backend:vulner
          #  image-ref: '${{ secrets.registry_endpoint }}/${{secrets.registry_team}}/${{secrets.registry_project}}:main'
            format: 'sarif'
            output: 'trivy-results.sarif'
            
        - name: list file
          run: ls -l;pwd
          
        - name: Upload Trivy scan results to GitHub Security tab
          id: run-analysis
          uses: github/codeql-action/upload-sarif@v2
          with:
            sarif_file: 'trivy-results.sarif'
            
        - name: Upload SARIF as an Artifact
          uses: actions/upload-artifact@v2
          with:
            name: sarif-file
            path: 'trivy-results.sarif'
